import Head from 'next/head'
import { useEffect } from 'react'

interface displayRadians {
  numerator: number,
  denominator: number
}

export default function Home() {
  const lines = [0, 30, 45, 60, 90, 120, 135, 150, 180, 210, 225, 240, 270, 300, 315, 330]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6 flex justify-center place-content-center content-center">
        <div className="h-[40rem] w-[40rem] border-2 border-black rounded-full relative">
          {lines.map((deg) => (
            <Line key={deg} degree={deg} />
          ))}
        </div>
      </main>

      <footer className="absolute bottom-0 w-screen left-0 p-2 flex flex-row justify-center">
        <a
          className="text-slate-500 underline text-center"
          href="https://github.com/BlueZeeKing"
        >
          BlueZeeKing24
        </a>
      </footer>
    </>
  );
}

function Line(props) {
  const radians = degreesToDisplayRadians(props.degree);
  return (
    <div
      className="w-[50%] absolute top-[50%] left-[50%] text-center h-0 border border-black origin-left"
      style={{ transform: `translateY(-50%) rotate(-${props.degree}deg)` }}
    >
      <div className="relative w-full">
        <span
          className="absolute bg-white px-2 left-[40%]"
          style={{ transform: `translateY(-50%) rotate(${props.degree}deg)` }} // rotate(${props.degree})
        >
          {props.degree}º
        </span>
        <FractionDisplay degree={props.degree} />
      </div>
    </div>
  );
}

function FractionDisplay(props) {
  const radians = degreesToDisplayRadians(props.degree);

  return (
    <span
      className="absolute bg-white px-2 left-[60%]"
      style={{ transform: `translateY(-50%) rotate(${props.degree}deg)` }}
    >
      {
        radians.numerator == 0 ? 0 :
        <>
          {radians.numerator != 1 ? radians.numerator : ""}π
          <hr className="border-black" />
          {radians.denominator}
        </>
      }
    </span>
  );
}

function degreesToDisplayRadians(degs: number): displayRadians {
  let gcd = findGCD(degs, 180);
  return {
    numerator: degs / gcd,
    denominator: 180 / gcd,
  };
}

function findGCD(a, b) {
  return b ? findGCD(b, a % b) : a;
}